server:
  port: 8084

spring:
  kafka:
    bootstrap-servers:
      - 127.0.0.1:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: test-consumer-group
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      default-topic: graduate

myConfiguration:
  securityHttpProtocol: "https"
  defaultHttpProtocol: "http:"
  httpPrefixRegex: "^http[s]?:"
  hrefRegex: "^http[s]?://[^.]+.[^.]+.[^/]+.+"
  fileProtocolPrefix: "file://"
  fileProtocolRegex: "^file://.+"
  #  匹配那些没有协议前缀的 URL
  urlRegex: "//[a-z|A-Z0-9]+.[^.]+.[a-z|A-Z]+"
  #  note: 确保设置了对应的浏览器程序的环境变量
  browser: "google-chrome"
  trustableRemoteAddr:
    - 127.0.0.1
    - 192.168.0.104